name: Build Release

on:
    workflow_dispatch:

jobs:
    build:
        name: Build Snow Release APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2
            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  distribution: 'zulu'
                  java-version: 21
                  cache: gradle
            - name: Write sign info
              run: |
                  if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
                      echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
                      echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
                      echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
                      echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
                      echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/keystore.jks
                    fi
            - name: Get Gradle
              run: gradle wrapper
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build Release apk
              run: ./gradlew assembleRelease --stacktrace
